# Generated by Django 5.0.6 on 2024-06-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('certification', models.TextField()),
                ('project_title', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_img', models.ImageField(upload_to='project_pics/')),
                ('project_link', models.CharField(max_length=100)),
            ],
        ),
    ]
